CREATE TABLE USERS_ACTR
(
    ID                  bigserial PRIMARY KEY,
    FIRST_NAME          VARCHAR(64)         NOT NULL,
    LAST_NAME           VARCHAR(64)         NOT NULL,

    USERNAME            VARCHAR(64) UNIQUE  NOT NULL,
    EMAIL               VARCHAR(128) UNIQUE NOT NULL,
    ENCRYPTED_PASSWORD  VARCHAR(64)         NOT NULL,
    USER_ID             VARCHAR(64) UNIQUE  NOT NULL,
    USER_ROLE_ID        BIGINT              NOT NULL,
    ORGANIZATION_ID     BIGINT              NOT NULL,
    DOMAIN_NAME         VARCHAR(64)  NOT NULL,
    LOGGED_OUT_AT       TIMESTAMP(6),
    STATUS              VARCHAR(32) DEFAULT 'ACTIVE',
    USER_TYPE           VARCHAR(16) NOT NULL,
    USER_CATEGORY       VARCHAR(32) NOT NULL,

    CREATED_BY          VARCHAR(64)         NOT NULL,
    CREATE_TIME         TIMESTAMP(6),
    EDITED_BY           VARCHAR(64),
    EDIT_TIME           TIMESTAMP(6),

    INTERNAL_VERSION    BIGINT      DEFAULT 0
);
CREATE SEQUENCE USERS_ACTR_SEQ INCREMENT BY 2 START WITH 1 NO CYCLE OWNED BY USERS_ACTR.ID;

CREATE TABLE ROLES_ACTR
(
    ID                  bigserial PRIMARY KEY,
    ROLE_NAME           VARCHAR(64)         NOT NULL,
    STATUS              VARCHAR(64)         NOT NULL,
    DESCRIPTION         VARCHAR(64)         NOT NULL,
    PRIORITY            INT,

    CREATED_BY          VARCHAR(64)         NOT NULL,
    CREATE_TIME         TIMESTAMP(6),
    EDITED_BY           VARCHAR(64),
    EDIT_TIME           TIMESTAMP(6),

    INTERNAL_VERSION    BIGINT      DEFAULT 0
);
CREATE SEQUENCE ROLES_ACTR_SEQ INCREMENT BY 2 START WITH 1 NO CYCLE OWNED BY ROLES_ACTR.ID;

CREATE TABLE PRIVILEGE_ACTR
(
    ID                      bigserial PRIMARY KEY,
    PRIVILEGE_NAME          VARCHAR(64)         NOT NULL,
    DESCRIPTION             VARCHAR(64)         NOT NULL,
    STATUS                  VARCHAR(64)         NOT NULL,
    PRIVILEGE_GROUP_ID      BIGINT              NOT NULL,
    API_END_POINT           VARCHAR(512)        NOT NULL,

    CREATED_BY              VARCHAR(64)         NOT NULL,
    CREATE_TIME             TIMESTAMP(6),
    EDITED_BY               VARCHAR(64),
    EDIT_TIME               TIMESTAMP(6),

    INTERNAL_VERSION        BIGINT      DEFAULT 0
);
CREATE SEQUENCE PRIVILEGE_ACTR_SEQ INCREMENT BY 2 START WITH 1 NO CYCLE OWNED BY PRIVILEGE_ACTR.ID;

CREATE TABLE ROLE_PRIVILEGE_MAPPING_ACTR
(
    ID                  bigserial PRIMARY KEY,
    ROLE_ID             BIGINT       NOT NULL,
    PRIVILEGE_ID        BIGINT       NOT NULL,
    INTERNAL_VERSION    BIGINT      DEFAULT 0
);
CREATE SEQUENCE ROLE_PRIVILEGE_MAPPING_ACTR_SEQ INCREMENT BY 2 START WITH 1 NO CYCLE OWNED BY ROLE_PRIVILEGE_MAPPING_ACTR.ID;


CREATE TABLE PRIVILEGE_GROUP_ACTR
(
    ID                      BIGSERIAL PRIMARY KEY,
    PRIVILEGE_GROUP_NAME    VARCHAR(512) NOT NULL,

    CREATED_BY       VARCHAR(64)  NOT NULL,
    CREATE_TIME      TIMESTAMP(6),
    EDITED_BY        VARCHAR(64),
    EDIT_TIME        TIMESTAMP(6),

    INTERNAL_VERSION BIGINT DEFAULT 0
);

CREATE SEQUENCE PRIVILEGE_GROUP_ACTR_SEQ INCREMENT BY 2 START WITH 1 NO CYCLE OWNED BY PRIVILEGE_GROUP_ACTR.ID;

CREATE TABLE PRIVILEGE_GROUP_PRIVILEGE_MAPPING_ACTR
(
    ID               BIGSERIAL PRIMARY KEY,
    GROUP_ID         BIGINT       NOT NULL,
    PRIVILEGE_ID     BIGINT       NOT NULL,

    CREATED_BY       VARCHAR(64) NOT NULL,
    CREATE_TIME      TIMESTAMP(6),
    EDITED_BY        VARCHAR(64),
    EDIT_TIME        TIMESTAMP(6),

    INTERNAL_VERSION BIGINT DEFAULT 0
);


