CREATE TABLE FAILED_EMAILS_ACTR
(
    ID              BIGSERIAL PRIMARY KEY,
    TO_MAILS        VARCHAR(1024) NOT NULL,
    CC_MAILS        VARCHAR(1024) NOT NULL,
    SUBJECT         VARCHAR(1024) NOT NULL,
    BODY            VARCHAR(1024) NOT NULL,
    FAILED_CAUSE    VARCHAR(1024) NOT NULL
);
CREATE SEQUENCE FAILED_EMAILS_ACTR_SEQ INCREMENT BY 2 START WITH 1 NO CYCLE OWNED BY FAILED_EMAILS_ACTR.ID;
